name: Unity C# Linter

on:
  push:  # Trigger on every push
  pull_request:  # Also run on pull requests

jobs:
  lint:
    name: Run C# Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: List Repository Files
        run: dir

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: Run dotnet format
        run: dotnet format Assets/Scripts --include **/*.cs --verbosity diagnostic
