name: Unity C# Linter

on:
  push:  # Trigger on every push
  pull_request:  # Also run on pull requests

jobs:
  lint:
    name: Run C# Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'  # Adjust to the required .NET version for Unity

      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format